#!/usr/bin/env bash
check_factor() {
    if [ $# -ne 3 ]; then
        args=("$@")
        num1=${args[1]}
        num2=1

        for ((i = 2; i <= $#; i++)); do
            num2=$((num2 * ${args[i]}))
        done
    else
        num1=${args[1]}
        num2=$3
    fi

    if [ "$num2" -gt "$num1" ]; then
        temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i")
        check_factor $result
    done < "$1"
fi
